"""Render approved Deep Ocean OLED assets without stretching font glyphs.

Usage: python3 scripts/render-retro-lcd-assets.py
The retained artwork uses black panels and Deep Ocean accents.
"""
import json
import math
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
ROOT = Path(__file__).resolve().parents[1]
PROJECT = ROOT / 'src/watchfaces/retro-lcd'
ASSETS = PROJECT / 'assets/balance-2-xt'
LAYOUT = json.loads((PROJECT / 'watchface/layout.json').read_text())
(PROJECT / 'watchface/layout.js').write_text('// Generated by scripts/render-retro-lcd-assets.py from layout.json.\nexport const LAYOUT = ' + json.dumps(LAYOUT, indent=2) + ';\n/** @param {string} style */\nexport function fontArray(style) {\n  return Array.from({ length: 10 }, (_, digit) => `digits/${style}/${digit}.png`);\n}\n')
S = 4
INK = '#e8edf0'
GRAY = '#66747e'
DSEG = PROJECT / 'fonts/DSEG7Classic-Bold.ttf'
LABEL = PROJECT / 'fonts/SpaceGrotesk-Bold.ttf'
STYLES = {'time':60,'date':28,'alarm':22,'seconds':26,'aod':60,'aod-date':28,'temperature':38,'range':20,'sleep':36}
def canvas(w,h): return Image.new('RGBA',(w*S,h*S))
def downsample(im, size):
    if 'ink' in im.info:
        result = Image.new('RGBA',size,im.info['ink'])
        result.putalpha(im.getchannel('A').resize(size,Image.Resampling.LANCZOS))
        return result
    return im.resize(size,Image.Resampling.LANCZOS)
def save(im,path):
    path.parent.mkdir(parents=True,exist_ok=True)
    downsample(im,(im.width//S,im.height//S)).save(path)
def ink_mask(value, font):
    # Render outside the nominal advance/ascent box before measuring actual ink.
    left,top,right,bottom = font.getbbox(value,anchor='ls')
    pad = 4*S
    mask = Image.new('L',(max(1,right-left)+2*pad,max(1,bottom-top)+2*pad))
    ImageDraw.Draw(mask).text((pad-left,pad-top),value,font=font,fill=255,anchor='ls')
    box = mask.getbbox()
    if not box:
        return None, 0, 0, 0
    return mask.crop(box), left+box[0]-pad, top+box[1]-pad, top+box[3]-pad
def character_name(char):return {'-':'dash',':':'colon','.':'dot','°':'degree','/':'slash',' ':'blank'}.get(char,char)
glyph_widths = {}
date_ink_bounds = {}
for style,size in STYLES.items():
    glyph_widths[style] = {}
    font=ImageFont.truetype(str(DSEG),size*S)
    color = '#9ba49d' if style=='aod' else '#747b76' if style=='aod-date' else INK
    measured = {char:ink_mask(char,font) for char in '0123456789-:.°C '}
    widths = {char:max(1,round(font.getlength(char)/S)) for char in measured}
    # DSEG's decimal point has zero advance but still has visible ink.
    widths['.'] = math.ceil(measured['.'][0].width/S)+2
    top = min(y for mask,_,y,_ in measured.values() if mask)
    bottom = max(y for mask,_,_,y in measured.values() if mask)
    scale = min(1,(size*S-2*S)/(bottom-top),
                *((widths[c]*S/2-S)/max(abs(x-widths[c]*S/2),abs(x+mask.width-widths[c]*S/2))
                  for c,(mask,x,_,_) in measured.items() if mask and c != '.'))
    for char,(mask,x,y,_) in measured.items():
        width=widths[char]
        glyph_widths[style][character_name(char)] = width
        alpha=Image.new('L',(width*S,size*S))
        if mask:
            fitted=mask.resize((max(1,round(mask.width*scale)),max(1,round(mask.height*scale))),Image.Resampling.LANCZOS)
            position_x = (alpha.width-fitted.width)//2 if char == '.' else round((alpha.width-alpha.width*scale)/2+x*scale)
            alpha.paste(fitted,(position_x,S+round((y-top)*scale)))
        glyph=Image.new('RGBA',(width,size),color)
        glyph.putalpha(alpha.resize((width,size),Image.Resampling.LANCZOS))
        path=ASSETS/f'digits/{style}/{character_name(char)}.png'
        path.parent.mkdir(parents=True,exist_ok=True);glyph.save(path)
        if style == 'date':
            box = glyph.getchannel('A').point(lambda alpha: 255 if alpha >= 32 else 0).getbbox()
            if box:
                date_ink_bounds[character_name(char)] = {'left':box[0],'right':box[2]}
    width=max(8,round(size*0.65))
    slash=canvas(width,size);slash.info['ink']=color
    stroke=max(S,round(size*0.08*S))
    inset=math.ceil(stroke/2)+S
    ImageDraw.Draw(slash).line((inset,size*S-inset,width*S-inset,inset),fill=color,width=stroke)
    save(slash,ASSETS/f'digits/{style}/slash.png');glyph_widths[style]['slash']=width

def label(value,w,h,size,color):
    font=ImageFont.truetype(str(LABEL),size*S)
    mask,_,_,_=ink_mask(value,font)
    im=canvas(w,h);im.info['ink']=color
    if mask:
        scale=min(1,(w*S-2*S)/mask.width,(h*S-2*S)/mask.height)
        mask=mask.resize((max(1,round(mask.width*scale)),max(1,round(mask.height*scale))),Image.Resampling.LANCZOS)
        alpha=Image.new('L',im.size)
        alpha.paste(mask,((im.width-mask.width)//2,(im.height-mask.height)//2))
        im=Image.new('RGBA',im.size,color);im.putalpha(alpha);im.info['ink']=color
    return im
for locale,days in [('en',['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY']),('it',['LUNEDI','MARTEDI','MERCOLEDI','GIOVEDI','VENERDI','SABATO','DOMENICA'])]:
    for mode,size,color in [('',24,INK),('aod-',24,'#747b76')]:
        for i,value in enumerate(days):save(label(value[:3],98,24,size,color),ASSETS/f'week/{mode}{locale}/{i+1}.png')
        save(label('---',98,20,size,color),ASSETS/f'week/{mode}{locale}/unknown.png')
save(label('SEC',34,16,14,GRAY),ASSETS/'status/sec.png')
for value in ['AM','PM','--']:save(label(value,46,18,18,GRAY),ASSETS/f'period/{value}.png')
save(canvas(46,18),ASSETS/'period/blank.png')
for value,width in [('ALM',43),('SIG',44),('MUTE',53)]:
    save(label(value,width,18,16,INK),ASSETS/f'status/{value.lower()}.png')
save(label('SIG',44,14,13,GRAY),ASSETS/'status/sig-off.png')
background=Image.open(PROJECT/'background-source.png').convert('RGB')
mask=Image.new('L',(480,480));ImageDraw.Draw(mask).ellipse((2,2,478,478),fill=255)
background=Image.composite(background,Image.new('RGB',(480,480),'black'),mask)
# The gray idle status belongs to the same curved cells as its active overlay.
for key,value,width in [('alarmStatus','ALM',43),('signalStatus','SIG',44),('muteStatus','MUTE',53)]:
    l=LAYOUT[key];im=downsample(label(value,width,18,16,GRAY),(width,18));background.paste(im,(l['x'],l['y']),im)
background.save(ASSETS/'background.png')
l=LAYOUT['signalStatus'];tile=background.crop((l['x'],l['y'],l['x']+44,l['y']+18)).convert('RGBA');tile.save(ASSETS/'status/sig-off.png')
for level in range(11):
    im=canvas(76,24);d=ImageDraw.Draw(im)
    d.rounded_rectangle((0,5*S,76*S-1,19*S-1),radius=3*S,fill='#182126')
    if level: d.rounded_rectangle((0,5*S,round(76*S*level/10)-1,19*S-1),radius=3*S,fill='#a2adb4')
    save(im,ASSETS/f'battery/{level}.png')
# Transparent arc frames overlay the retained tracks. Icons are separate upper widgets.
for kind,radius,width in [('steps',73,20),('calories',49,20),('active',25,20)]:
    for level in range(101):
        im=canvas(166,166);d=ImageDraw.Draw(im)
        if level:
            outer=radius+width/2
            box=((83-outer)*S,(83-outer)*S,(83+outer)*S,(83+outer)*S)
            d.arc(box,-90,-90+level*3.6,fill={'steps': '#62c7d4', 'calories': '#3598aa', 'active': '#216374'}[kind],width=width*S)
            if level<100:
                for angle in [-90,-90+level*3.6]:
                    x=83+math.cos(math.radians(angle))*radius
                    y=83+math.sin(math.radians(angle))*radius
                    d.ellipse(((x-width/2)*S,(y-width/2)*S,(x+width/2)*S,(y+width/2)*S),fill={'steps': '#62c7d4', 'calories': '#3598aa', 'active': '#216374'}[kind])
        save(im,ASSETS/f'ring/{kind}/{level}.png')
def paste(im,path,x,y):
    overlay=Image.open(ASSETS/path).convert('RGBA');im.paste(overlay,(round(x),round(y)),overlay)
def text(im,value,center,y,style):
    images=[Image.open(ASSETS/f'digits/{style}/{character_name(c)}.png') for c in value]
    x=round(center-sum(i.width for i in images)/2)
    for c,img in zip(value,images):paste(im,f'digits/{style}/{character_name(c)}.png',x,y);x+=img.width
def date_text(im,value,aod):
    layout=LAYOUT['aodDate' if aod else 'date']
    style='aod-date' if aod else 'date'
    for char,x in zip(value,layout['digits']):
        paste(im,f'digits/{style}/{char}.png',x,layout['y'])
    day=date_ink_bounds[value[1]];month=date_ink_bounds[value[2]];dash=date_ink_bounds['dash']
    x=round((layout['digits'][1]+day['right']+layout['digits'][2]+month['left']-dash['left']-dash['right'])/2)
    paste(im,f'digits/{style}/dash.png',x,layout['y'])
normal=background.copy()
for kind,level in [('steps',82),('calories',81),('active',75)]:paste(normal,f'ring/{kind}/{level}.png',61,57)
for icon in LAYOUT['rings']['icons']:paste(normal,f"icons/{icon['name']}.png",icon['x'],icon['y'])
text(normal,'18:19',284,285,'time');date_text(normal,'0110',False);text(normal,'23',409,319,'seconds');text(normal,'07:00',125,288,'alarm')
text(normal,'17',330,70,'temperature');text(normal,'°',365,66,'range');text(normal,'12° - 21°C',343,120,'range');text(normal,'7:24',383,181,'sleep')
paste(normal,'weather/0.png',263,75);battery_preview=Image.open(ASSETS/'battery/6.png').convert('RGBA').resize((76,24),Image.Resampling.LANCZOS);normal.paste(battery_preview,(87,322),battery_preview);paste(normal,'status/sec.png',392,296);paste(normal,'week/it/4.png',129,380)
for key,value in [('alarmStatus','alm'),('signalStatus','sig')]:l=LAYOUT[key];paste(normal,f'status/{value}.png',l['x'],l['y'])
preview=ROOT/'docs/previews';preview.mkdir(parents=True,exist_ok=True);normal.save(preview/'retro-lcd-normal.png');normal.resize((324,324),Image.Resampling.LANCZOS).save(ASSETS/'icon.png')
aod=Image.new('RGB',(480,480),'black');text(aod,'18:19',284,285,'aod');date_text(aod,'0110',True);paste(aod,'week/aod-it/4.png',129,380);aod.save(preview/'retro-lcd-aod.png')

with (PROJECT / 'watchface/layout.js').open('a') as output:
    output.write('/** @type {Record<string, Record<string, number>>} */\nexport const GLYPH_WIDTHS = ' + json.dumps(glyph_widths,indent=2) + ';\n')

with (PROJECT / 'watchface/layout.js').open('a') as output:
    output.write('/** @type {Record<string, {left:number,right:number}>} */\nexport const DATE_INK_BOUNDS = ' + json.dumps(date_ink_bounds,indent=2) + ';\n')
