"""Render approved circular LCD assets without stretching font glyphs.

Usage: python3 scripts/render-retro-lcd-assets.py
The retained SVG and its raster background share the approved Casio gray palette.
"""
import json
import math
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
ROOT = Path(__file__).resolve().parents[1]
PROJECT = ROOT / 'src/watchfaces/retro-lcd'
ASSETS = PROJECT / 'assets/balance-2-xt'
LAYOUT = json.loads((PROJECT / 'watchface/layout.json').read_text())
(PROJECT / 'watchface/layout.js').write_text('// Generated by scripts/render-retro-lcd-assets.py from layout.json.\nexport const LAYOUT = ' + json.dumps(LAYOUT, indent=2) + ';\n/** @param {string} style */\nexport function fontArray(style) {\n  return Array.from({ length: 10 }, (_, digit) => `digits/${style}/${digit}.png`);\n}\n')
S = 4
INK = '#080a0a'
GRAY = '#343e32'
DSEG = PROJECT / 'fonts/DSEG7Classic-Bold.ttf'
LABEL = PROJECT / 'fonts/SpaceGrotesk-Bold.ttf'
STYLES = {'time':70,'date':28,'alarm':24,'seconds':26,'aod':70,'aod-date':28,'temperature':38,'range':20,'sleep':36}
def canvas(w,h): return Image.new('RGBA',(w*S,h*S))
def save(im,path):
    path.parent.mkdir(parents=True,exist_ok=True)
    im.resize((im.width//S,im.height//S),Image.Resampling.LANCZOS).save(path)
def character_name(char):return {'-':'dash',':':'colon','.':'dot','°':'degree','/':'slash',' ':'blank'}.get(char,char)
glyph_widths = {}
for style,size in STYLES.items():
    glyph_widths[style] = {}
    font=ImageFont.truetype(str(DSEG),size)
    color = '#9ba49d' if style=='aod' else '#747b76' if style=='aod-date' else INK
    for char in '0123456789-:.°/C ':
        # Preserve the font's native advance and baseline at every size.
        width=max(1,round(font.getlength(char)))
        glyph_widths[style][character_name(char)] = width
        im=Image.new('RGBA',(width,size))
        if char == '/':
            width=max(8,round(size*0.65));im=Image.new('RGBA',(width,size))
            ImageDraw.Draw(im).line((2,size-2,width-2,2),fill=color,width=max(S,round(size*0.08)))
            glyph_widths[style]['slash']=width
        else:
            ImageDraw.Draw(im).text((0,size),char,font=font,fill=color,anchor='ls')
        path=ASSETS/f'digits/{style}/{character_name(char)}.png';path.parent.mkdir(parents=True,exist_ok=True);im.save(path)
def label(value,w,h,size,color):
    im=canvas(w,h);d=ImageDraw.Draw(im);font=ImageFont.truetype(str(LABEL),size*S)
    left,top,right,bottom=d.textbbox((0,0),value,font=font)
    d.text(((w*S-(right-left))/2-left,(h*S-(bottom-top))/2-top),value,font=font,fill=color)
    return im
for locale,days in [('en',['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY']),('it',['LUNEDI','MARTEDI','MERCOLEDI','GIOVEDI','VENERDI','SABATO','DOMENICA'])]:
    for mode,size,color in [('',24,INK),('aod-',24,'#747b76')]:
        for i,value in enumerate(days):save(label(value[:3],98,24,size,color),ASSETS/f'week/{mode}{locale}/{i+1}.png')
        save(label('---',98,20,size,color),ASSETS/f'week/{mode}{locale}/unknown.png')
save(label('SEC',34,16,14,GRAY),ASSETS/'status/sec.png')
for value in ['AM','PM','--']:save(label(value,46,18,18,GRAY),ASSETS/f'period/{value}.png')
save(canvas(46,18),ASSETS/'period/blank.png')
for value,width in [('ALM',43),('SIG',44),('MUTE',53)]:
    save(label(value,width,18,16,INK),ASSETS/f'status/{value.lower()}.png')
save(label('SIG',44,14,13,GRAY),ASSETS/'status/sig-off.png')
background=Image.open(PROJECT/'background-source.png').convert('RGB')
mask=Image.new('L',(480,480));ImageDraw.Draw(mask).ellipse((2,2,478,478),fill=255)
background=Image.composite(background,Image.new('RGB',(480,480),'black'),mask)
# The gray idle status belongs to the same curved cells as its active overlay.
for key,value,width in [('alarmStatus','ALM',43),('signalStatus','SIG',44),('muteStatus','MUTE',53)]:
    l=LAYOUT[key];im=label(value,width,18,16,GRAY).resize((width,18),Image.Resampling.LANCZOS);background.paste(im,(l['x'],l['y']),im)
background.save(ASSETS/'background.png')
l=LAYOUT['signalStatus'];tile=background.crop((l['x'],l['y'],l['x']+44,l['y']+18)).convert('RGBA');tile.save(ASSETS/'status/sig-off.png')
for level in range(11):
    im=canvas(68,20);d=ImageDraw.Draw(im)
    for i in range(10):d.rectangle((i*7*S,0,(i*7+5)*S-1,20*S-1),fill=INK if i<level else '#75816d')
    save(im,ASSETS/f'battery/{level}.png')
# Transparent arc frames overlay the retained tracks. Icons are separate upper widgets.
for kind,radius,width in [('steps',73,20),('calories',49,20),('active',25,20)]:
    for level in range(101):
        im=canvas(166,166);d=ImageDraw.Draw(im)
        if level:
            outer=radius+width/2
            box=((83-outer)*S,(83-outer)*S,(83+outer)*S,(83+outer)*S)
            d.arc(box,-90,-90+level*3.6,fill='#8b9984',width=width*S)
            if level<100:
                for angle in [-90,-90+level*3.6]:
                    x=83+math.cos(math.radians(angle))*radius
                    y=83+math.sin(math.radians(angle))*radius
                    d.ellipse(((x-width/2)*S,(y-width/2)*S,(x+width/2)*S,(y+width/2)*S),fill='#8b9984')
        save(im,ASSETS/f'ring/{kind}/{level}.png')
def paste(im,path,x,y):
    overlay=Image.open(ASSETS/path).convert('RGBA');im.paste(overlay,(round(x),round(y)),overlay)
def text(im,value,center,y,style):
    images=[Image.open(ASSETS/f'digits/{style}/{character_name(c)}.png') for c in value]
    x=round(center-sum(i.width for i in images)/2)
    for c,img in zip(value,images):paste(im,f'digits/{style}/{character_name(c)}.png',x,y);x+=img.width
normal=background.copy()
for kind,level in [('steps',82),('calories',81),('active',75)]:paste(normal,f'ring/{kind}/{level}.png',61,57)
for icon in LAYOUT['rings']['icons']:paste(normal,f"icons/{icon['name']}.png",icon['x'],icon['y'])
text(normal,'18:19',221,303,'time');text(normal,'01/10',267,387,'date');text(normal,'23',367,347,'seconds');text(normal,'07:00',171,266,'alarm')
text(normal,'17',330,70,'temperature');text(normal,'°',365,66,'range');text(normal,'12° / 21°C',343,120,'range');text(normal,'7:24',383,181,'sleep')
paste(normal,'weather/0.png',265,77);battery_preview=Image.open(ASSETS/'battery/6.png').convert('RGBA').resize((68,20),Image.Resampling.LANCZOS);normal.paste(battery_preview,(313,268),battery_preview);paste(normal,'status/sec.png',350,324);paste(normal,'week/it/4.png',129,391)
for key,value in [('alarmStatus','alm'),('signalStatus','sig')]:l=LAYOUT[key];paste(normal,f'status/{value}.png',l['x'],l['y'])
preview=ROOT/'docs/previews';preview.mkdir(parents=True,exist_ok=True);normal.save(preview/'retro-lcd-normal.png');normal.resize((324,324),Image.Resampling.LANCZOS).save(ASSETS/'icon.png')
aod=Image.new('RGB',(480,480),'black');text(aod,'18:19',221,303,'aod');text(aod,'01/10',267,387,'aod-date');paste(aod,'week/aod-it/4.png',129,391);aod.save(preview/'retro-lcd-aod.png')

with (PROJECT / 'watchface/layout.js').open('a') as output:
    output.write('/** @type {Record<string, Record<string, number>>} */\nexport const GLYPH_WIDTHS = ' + json.dumps(glyph_widths,indent=2) + ';\n')
