// Generated by scripts/render-retro-lcd-assets.py from layout.json.
export const LAYOUT = {
  "time": {
    "digits": [
      100,
      157,
      228,
      285
    ],
    "colon": 214,
    "y": 303
  },
  "date": {
    "digits": [
      212,
      235,
      276,
      299
    ],
    "dash": 258,
    "y": 387
  },
  "weekday": {
    "x": 129,
    "y": 391
  },
  "period": {
    "x": 205,
    "y": 276
  },
  "seconds": {
    "x": 346,
    "y": 347
  },
  "secondsLabel": {
    "x": 350,
    "y": 324
  },
  "alarm": {
    "x": 129,
    "y": 266,
    "w": 85,
    "h": 24
  },
  "battery": {
    "x": 313,
    "y": 268
  },
  "alarmStatus": {
    "x": 150,
    "y": 435
  },
  "signalStatus": {
    "x": 218,
    "y": 435
  },
  "muteStatus": {
    "x": 282,
    "y": 435
  },
  "rings": {
    "x": 61,
    "y": 57,
    "icons": [
      {
        "x": 135,
        "y": 58,
        "name": "footprints"
      },
      {
        "x": 135,
        "y": 82,
        "name": "flame"
      },
      {
        "x": 135,
        "y": 106,
        "name": "timer"
      }
    ]
  },
  "weather": {
    "x": 265,
    "y": 77,
    "temperature": {
      "center": 330,
      "y": 70,
      "style": "temperature",
      "length": 3
    },
    "range": {
      "center": 343,
      "y": 120,
      "style": "range",
      "length": 12
    }
  },
  "sleep": {
    "center": 383,
    "y": 181,
    "style": "sleep",
    "length": 5
  },
  "aod": {
    "digits": [
      100,
      157,
      228,
      285
    ],
    "colon": 214,
    "y": 303,
    "weekday": {
      "x": 129,
      "y": 391
    }
  },
  "aodDate": {
    "digits": [
      212,
      235,
      276,
      299
    ],
    "dash": 258,
    "y": 387
  }
};
/** @param {string} style */
export function fontArray(style) {
  return Array.from({ length: 10 }, (_, digit) => `digits/${style}/${digit}.png`);
}
/** @type {Record<string, Record<string, number>>} */
export const GLYPH_WIDTHS = {
  "time": {
    "0": 57,
    "1": 57,
    "2": 57,
    "3": 57,
    "4": 57,
    "5": 57,
    "6": 57,
    "7": 57,
    "8": 57,
    "9": 57,
    "dash": 57,
    "colon": 14,
    "dot": 1,
    "degree": 57,
    "slash": 46,
    "C": 57,
    "blank": 14
  },
  "date": {
    "0": 23,
    "1": 23,
    "2": 23,
    "3": 23,
    "4": 23,
    "5": 23,
    "6": 23,
    "7": 23,
    "8": 23,
    "9": 23,
    "dash": 23,
    "colon": 6,
    "dot": 1,
    "degree": 23,
    "slash": 18,
    "C": 23,
    "blank": 6
  },
  "alarm": {
    "0": 20,
    "1": 20,
    "2": 20,
    "3": 20,
    "4": 20,
    "5": 20,
    "6": 20,
    "7": 20,
    "8": 20,
    "9": 20,
    "dash": 20,
    "colon": 5,
    "dot": 1,
    "degree": 20,
    "slash": 16,
    "C": 20,
    "blank": 5
  },
  "seconds": {
    "0": 21,
    "1": 21,
    "2": 21,
    "3": 21,
    "4": 21,
    "5": 21,
    "6": 21,
    "7": 21,
    "8": 21,
    "9": 21,
    "dash": 21,
    "colon": 5,
    "dot": 1,
    "degree": 21,
    "slash": 17,
    "C": 21,
    "blank": 5
  },
  "aod": {
    "0": 57,
    "1": 57,
    "2": 57,
    "3": 57,
    "4": 57,
    "5": 57,
    "6": 57,
    "7": 57,
    "8": 57,
    "9": 57,
    "dash": 57,
    "colon": 14,
    "dot": 1,
    "degree": 57,
    "slash": 46,
    "C": 57,
    "blank": 14
  },
  "aod-date": {
    "0": 23,
    "1": 23,
    "2": 23,
    "3": 23,
    "4": 23,
    "5": 23,
    "6": 23,
    "7": 23,
    "8": 23,
    "9": 23,
    "dash": 23,
    "colon": 6,
    "dot": 1,
    "degree": 23,
    "slash": 18,
    "C": 23,
    "blank": 6
  },
  "temperature": {
    "0": 31,
    "1": 31,
    "2": 31,
    "3": 31,
    "4": 31,
    "5": 31,
    "6": 31,
    "7": 31,
    "8": 31,
    "9": 31,
    "dash": 31,
    "colon": 8,
    "dot": 1,
    "degree": 31,
    "slash": 25,
    "C": 31,
    "blank": 8
  },
  "range": {
    "0": 16,
    "1": 16,
    "2": 16,
    "3": 16,
    "4": 16,
    "5": 16,
    "6": 16,
    "7": 16,
    "8": 16,
    "9": 16,
    "dash": 16,
    "colon": 4,
    "dot": 1,
    "degree": 16,
    "slash": 13,
    "C": 16,
    "blank": 4
  },
  "sleep": {
    "0": 29,
    "1": 29,
    "2": 29,
    "3": 29,
    "4": 29,
    "5": 29,
    "6": 29,
    "7": 29,
    "8": 29,
    "9": 29,
    "dash": 29,
    "colon": 7,
    "dot": 1,
    "degree": 29,
    "slash": 23,
    "C": 29,
    "blank": 7
  }
};
