// Generated by scripts/render-retro-lcd-assets.py from layout.json.
export const LAYOUT = {
  "time": {
    "digits": [
      180,
      229,
      290,
      339
    ],
    "colon": 278,
    "y": 285
  },
  "date": {
    "digits": [
      210,
      233,
      279,
      302
    ],
    "dash": 256,
    "y": 376
  },
  "weekday": {
    "x": 129,
    "y": 380
  },
  "period": {
    "x": 275,
    "y": 258
  },
  "seconds": {
    "x": 388,
    "y": 319
  },
  "secondsLabel": {
    "x": 392,
    "y": 296
  },
  "alarm": {
    "x": 87,
    "y": 288,
    "w": 76,
    "h": 22
  },
  "battery": {
    "x": 87,
    "y": 322
  },
  "alarmStatus": {
    "x": 150,
    "y": 435
  },
  "signalStatus": {
    "x": 218,
    "y": 435
  },
  "muteStatus": {
    "x": 282,
    "y": 435
  },
  "rings": {
    "x": 61,
    "y": 57,
    "icons": [
      {
        "x": 138,
        "y": 58,
        "name": "footprints"
      },
      {
        "x": 138,
        "y": 82,
        "name": "flame"
      },
      {
        "x": 138,
        "y": 106,
        "name": "timer"
      }
    ]
  },
  "weather": {
    "x": 263,
    "y": 75,
    "temperature": {
      "center": 330,
      "y": 70,
      "style": "temperature",
      "length": 3
    },
    "range": {
      "center": 343,
      "y": 120,
      "style": "range",
      "length": 12
    }
  },
  "sleep": {
    "center": 383,
    "y": 181,
    "style": "sleep",
    "length": 5
  },
  "aod": {
    "digits": [
      180,
      229,
      290,
      339
    ],
    "colon": 278,
    "y": 285,
    "weekday": {
      "x": 129,
      "y": 380
    }
  },
  "aodDate": {
    "digits": [
      210,
      233,
      279,
      302
    ],
    "dash": 256,
    "y": 376
  }
};
/** @param {string} style */
export function fontArray(style) {
  return Array.from({ length: 10 }, (_, digit) => `digits/${style}/${digit}.png`);
}
/** @type {Record<string, Record<string, number>>} */
export const GLYPH_WIDTHS = {
  "time": {
    "0": 49,
    "1": 49,
    "2": 49,
    "3": 49,
    "4": 49,
    "5": 49,
    "6": 49,
    "7": 49,
    "8": 49,
    "9": 49,
    "dash": 49,
    "colon": 12,
    "dot": 10,
    "degree": 49,
    "C": 49,
    "blank": 12,
    "slash": 39
  },
  "date": {
    "0": 23,
    "1": 23,
    "2": 23,
    "3": 23,
    "4": 23,
    "5": 23,
    "6": 23,
    "7": 23,
    "8": 23,
    "9": 23,
    "dash": 23,
    "colon": 6,
    "dot": 6,
    "degree": 23,
    "C": 23,
    "blank": 6,
    "slash": 18
  },
  "alarm": {
    "0": 18,
    "1": 18,
    "2": 18,
    "3": 18,
    "4": 18,
    "5": 18,
    "6": 18,
    "7": 18,
    "8": 18,
    "9": 18,
    "dash": 18,
    "colon": 4,
    "dot": 5,
    "degree": 18,
    "C": 18,
    "blank": 4,
    "slash": 14
  },
  "seconds": {
    "0": 21,
    "1": 21,
    "2": 21,
    "3": 21,
    "4": 21,
    "5": 21,
    "6": 21,
    "7": 21,
    "8": 21,
    "9": 21,
    "dash": 21,
    "colon": 5,
    "dot": 6,
    "degree": 21,
    "C": 21,
    "blank": 5,
    "slash": 17
  },
  "aod": {
    "0": 49,
    "1": 49,
    "2": 49,
    "3": 49,
    "4": 49,
    "5": 49,
    "6": 49,
    "7": 49,
    "8": 49,
    "9": 49,
    "dash": 49,
    "colon": 12,
    "dot": 10,
    "degree": 49,
    "C": 49,
    "blank": 12,
    "slash": 39
  },
  "aod-date": {
    "0": 23,
    "1": 23,
    "2": 23,
    "3": 23,
    "4": 23,
    "5": 23,
    "6": 23,
    "7": 23,
    "8": 23,
    "9": 23,
    "dash": 23,
    "colon": 6,
    "dot": 6,
    "degree": 23,
    "C": 23,
    "blank": 6,
    "slash": 18
  },
  "temperature": {
    "0": 31,
    "1": 31,
    "2": 31,
    "3": 31,
    "4": 31,
    "5": 31,
    "6": 31,
    "7": 31,
    "8": 31,
    "9": 31,
    "dash": 31,
    "colon": 8,
    "dot": 7,
    "degree": 31,
    "C": 31,
    "blank": 8,
    "slash": 25
  },
  "range": {
    "0": 16,
    "1": 16,
    "2": 16,
    "3": 16,
    "4": 16,
    "5": 16,
    "6": 16,
    "7": 16,
    "8": 16,
    "9": 16,
    "dash": 16,
    "colon": 4,
    "dot": 5,
    "degree": 16,
    "C": 16,
    "blank": 4,
    "slash": 13
  },
  "sleep": {
    "0": 29,
    "1": 29,
    "2": 29,
    "3": 29,
    "4": 29,
    "5": 29,
    "6": 29,
    "7": 29,
    "8": 29,
    "9": 29,
    "dash": 29,
    "colon": 7,
    "dot": 7,
    "degree": 29,
    "C": 29,
    "blank": 7,
    "slash": 23
  }
};
/** @type {Record<string, {left:number,right:number}>} */
export const DATE_INK_BOUNDS = {
  "0": {
    "left": 3,
    "right": 20
  },
  "1": {
    "left": 16,
    "right": 20
  },
  "2": {
    "left": 3,
    "right": 20
  },
  "3": {
    "left": 4,
    "right": 20
  },
  "4": {
    "left": 3,
    "right": 20
  },
  "5": {
    "left": 3,
    "right": 20
  },
  "6": {
    "left": 3,
    "right": 20
  },
  "7": {
    "left": 3,
    "right": 20
  },
  "8": {
    "left": 3,
    "right": 20
  },
  "9": {
    "left": 3,
    "right": 20
  },
  "dash": {
    "left": 5,
    "right": 18
  },
  "colon": {
    "left": 1,
    "right": 5
  },
  "dot": {
    "left": 1,
    "right": 5
  },
  "degree": {
    "left": 3,
    "right": 20
  },
  "C": {
    "left": 3,
    "right": 18
  }
};
